FROM golang:1.20

WORKDIR /app

# Copy entire repo
COPY . .

# Force rebuild every time
RUN ls -la

# Install missing packages
RUN go get -u github.com/dgrijalva/jwt-go
RUN go get -u github.com/go-sql-driver/mysql
RUN go get -u github.com/gorilla/mux
RUN go get -u github.com/gorilla/websocket
RUN go get -u golang.org/x/crypto/argon2
RUN go get -u golang.org/x/crypto

# Build with full debugging
RUN GOOS=linux CGO_ENABLED=0 go build -v ./cmd/api/main.go

# Run the application
CMD ["./main"]